---

- name: grant sudo access to teams
  template: src=etc/sudoers.d/teams.j2
            dest=/etc/sudoers.d/teams
            mode=0444 owner=root group=root

# run team.yml once for each team to create
- include: team.yml
  with_items: "{{ ssh_teams }}"
  loop_control:
    loop_var: team
