---

# the 'team' var has been set to the team to create
#
- name: create account
  user: name={{ item }} group={{ team }}
        createhome=yes
  with_items: "{{ team_members[team] }}"

- name: set authorized_keys
  authorized_key: user={{ item }} exclusive=yes
                  key="{{ lookup('file', 'files/pubkeys/{{ item }}.key') }}"
  with_items: "{{ team_members[team] }}"
