---

# global list of SSH users by team.
# Corresponding public key at files/pubkeys/{{ user }}.key
#
team_members:
  dbas:
    - john
    - paul
    - george
    - ringo
  sysadmins:
    - shaggy
    - velma
    - fred
    - daphne
    - scooby
  webdevs:
    - salt
    - pepa
